### ISSUE TITLE
Build library

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/blockchain-k-plugin#152]
Discussions with @goodlyrottenapple and @jberthold led us to conclude we may want to build a combined library (statically?) that includes all the dependencies like cryptopp etc.

**Comment by gtrepta** [comment]
The PR that closed this issue introduced a [change](https://github.com/runtimeverification/blockchain-k-plugin/pull/173/commits/f859294ca5059ff9b4b06c3e0f863106cc7fe264) to the way that cryptopp is built which removes the `-fPIC` flag. I think we were relying on the cryptopp makefile to add this flag, but then we explicitly set the `CXXFLAGS` variable which overrides it.

For context, `-fPIC` tells the compiler to create position independent code that does jumps with relative positions in the code rather than absolute ones. This is needed for libraries because they have no guarantees for what address they get loaded into.
